services:
  app:
    image: openjdk:17-jdk-slim
    container_name: java_app
    working_dir: /app
    volumes:
      - ./src:/app/src:cached       # Mount your Java source code directory
      - ./build:/app/build:cached   # Optional: Mount your build output directory
    command: sh -c "while :; do sleep 10; done" # Keeps the container running
    ports:
      - "8080:8080"                 # Expose the application port
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fictional_events
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"                 # Expose Postgres port for connections

volumes:
  postgres_data:
    driver: local
