spring:
  application:
    name: events
  # datasource:
  #   url: 'jdbc:postgresql://localhost:5432/fictional_events'
  #   username: postgres
  # jpa:
  #   hibernate:
  #   ddl-auto: never
management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
info:
  app:
    name: Spring Boot Actuator Info Application
    description: Spring Boot application that explores the /info endpoint
    build: 1.0.0
