name: Build, Test, Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set Git committer identity
      run: |
        git config --global user.name "Kent Henneuse"
        git config --global user.email "khenneuse@users.noreply.github.com"

    - name: Get next version
      id: next_tag
      uses: anothrNick/github-tag-action@v1
      env:
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Tag branch
      if: success()
      env:
        VERSION: ${{steps.next_tag.outputs.tag}}
      run: |
        git tag -a ${VERSION} -m "Release ${VERSION}."
        git push origin ${VERSION}
        echo "tag ${VERSION} new_tag ${{steps.next_tag.outputs.new_tag}} old_tag ${{steps.next_tag.outputs.old_tag}}"

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
